blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/metovyura2/Dynamic-Head/discussions
    about: Ask a question or start a discussion about Dynamic-Head.
